### ISSUE TITLE
Subscribe and join buttons overlap

### ISSUE THREAD

**Issue by mattkdoggie** [tubearchivist/browser-extension#10]
The subscribe and join buttons overlap when there is not enough space horizontally. It also cuts off the channel info as well.

Example without join button - 
<img width="763" alt="Screenshot 2022-11-30 at 7 39 02 PM" src="https://user-images.githubusercontent.com/95995256/204945208-18b53a60-a7bd-48cf-ac80-5c33f5bbb861.png">

Example with join button - 
<img width="754" alt="Screenshot 2022-11-30 at 7 39 52 PM" src="https://user-images.githubusercontent.com/95995256/204945305-b34b753b-e933-4f7f-9985-908460672934.png">

**Comment by bbilly1** [comment]
I think I got this to behave nicer now. The channel name cut off is a YouTube thing. That will happen a bit sooner now with the additional button taking up space than it otherwise would. But I don't think we can avoid that. In any case, v0.1.1 will be out once it passes validations.

**Comment by mattkdoggie** [comment]
Looks better but I'm not getting the like button to overlap in some situations.
Example - 
<img width="673" alt="Screenshot 2022-12-02 at 7 46 03 AM" src="https://user-images.githubusercontent.com/95995256/205307311-26b6640b-1f90-4f51-af26-deae21195f81.png">

This is only happening in a very narrow width.

**Comment by bbilly1** [comment]
Sometimes it needs a page refresh for the other youtube buttons to realize there isn't enough space anymore, sometimes it doesn't trigger on window resize. If you want to keep tinkering with it, please do. We can always also finetuning it as we go.
