### ISSUE TITLE
No Subscribe or Download button when logged into Youtube

### ISSUE THREAD

**Issue by eddyz1122** [tubearchivist/browser-extension#15]
When signed into a Youtube/Google account, the subscribe and download button isnt injected.

This is how it appears when logged into a Google/Youtube Account.
![image](https://user-images.githubusercontent.com/56165935/212764739-06d458e0-7de1-4aa7-a0f7-61c255bc28b4.png)

This is how the same page appears after logging out of Google/Youtube Account.
![image](https://user-images.githubusercontent.com/56165935/212764842-56fb873a-31ce-4c24-904d-d8a19a9dd265.png)

**Comment by mon5termatt** [comment]
![image](https://user-images.githubusercontent.com/43628254/212787809-3d93ac63-3fec-40bf-9d1e-2e084e6e84af.png)
seems fine on my end

**Comment by eddyz1122** [comment]
> ![image](https://user-images.githubusercontent.com/43628254/212787809-3d93ac63-3fec-40bf-9d1e-2e084e6e84af.png) seems fine on my end

https://pbs.twimg.com/media/EC_XO-cX4AAFrO6.jpg 

Something must obviously be different. What browser are you using? I am using Firefox v108.0.2. The Youtube layout seems to change to the "new layout" when not signed in, but after signing in it reverts to some older layout.

**Comment by mon5termatt** [comment]
Chrome 109.0.5414.75

**Comment by mon5termatt** [comment]
> https://pbs.twimg.com/media/EC_XO-cX4AAFrO6.jpg

I test my personal code on vm's for that exact reason.

**Comment by bbilly1** [comment]
Looks like you didn't get the new layout, so the CSS selectors wont work to inject the buttons.

Not quite sure how you can force your browser to update, some google search suggest to edit the `PREF` cookie value. For me that's set to something like that:

```
f4=4000000&tz=my.timezone&f5=30000&f7=140&f6=40000000
```

Some suggest that `f6` is the relevant value, but who knows what it means, but you could try to tinker with that.

But all in all, this extension only work in the new layout.

**Comment by eddyz1122** [comment]
Seems that Google has blessed me with the new layout and the buttons are now visible.
