### ISSUE TITLE
Thumbnail download button with AR

### ISSUE THREAD

**Issue by Zyzto** [tubearchivist/browser-extension#16]
I think this an issue with only arabic language since it reverse the ui, where the download button covers the watch later button

![vivaldi_FMWIMwo059](https://user-images.githubusercontent.com/13531154/212833625-27dabe90-51cc-4159-9e41-2005e647bf13.gif)

**Comment by bbilly1** [comment]
That's very unfortunate. I think that needs somebody affected to come up with a solution, maybe this can be detected with a selector somehow?

**Comment by bbilly1** [comment]
that should now be fixed in v0.2.0 with the new selector.
