### ISSUE TITLE
Extension fails to show pop-up (most of the time) when clicking toolbar icon

### ISSUE THREAD

**Issue by mastoca** [tubearchivist/browser-extension#17]
I've tried both chromium & firefox with the same result.

Clicking the toolbar icon should present settings etc. but it hasn't done so since the recent update.

UPDATE: if you repeatedly click the toolbar icon it **sometimes** will show the proper popup instead of a tiny spec in the bottom right corner of the toolbar icon. (also refining the title of the bug as it may not just be new installs)

**Comment by bbilly1** [comment]
Hard to guess, why that happens for you. Can you can create an error message? For example for firefox: `about:debugging#/runtime/this-firefox` then click on `instpect` for the addon to open the debug tools.

**Comment by mastoca** [comment]
Thanks for the response. I installed the extension on another laptop and the popup appeared. Strangely, my computer started to work yesterday without any changes. I'm closing this ticket as I've been unable to reproduce it now.

Unclear what state my browser had gotten to. I'll reopen if it occurs and I'm able to get some debug logs etc.

Thanks for this awesome work from several members of our family and myself.
