### ISSUE TITLE
Extension fails to show pop-up 

### ISSUE THREAD

**Issue by bokerlol** [tubearchivist/browser-extension#20]
Duplicate of #17 but posting again as no real solution was given. 

On the same computer, not the computer hosting TA btw, both Chrome and Firefox refuse to show the login pop-up. I've tried through the official store install and the manifest.json. No matter what I do, it doesn't seem to show the pop-up. I'm at a loss as I've tried just about everything. I did however try on another PC and it showed up just fine so it must be something within my PC that is causing the issue but as to what it is, I have no idea. 

Any ideas?

Main PC is on Windows 10 64-bit. Both Chrome and Firefox fully up to date. Chrome has no other extensions installed also. 
Server with TA is on Unraid, fully up to date. 

Running in private windows on either browser has no effect on its functionality.

**Comment by bbilly1** [comment]
As mentioned in the linked issue, can you produce an error by inspecting the extension? 

Without an error and without a way to reproduce, I'm afraid there isn't much anybody can do.

**Comment by bokerlol** [comment]
I did attempt to create an error but none were produced, sadly.. I'm really not sure what is causing the issue but I'll keep tinkering with it. I've tried in multiple browsers at this point and it's the same on all of them so it has to be something with this PC that it doesn't like. 

Thanks for everything you all do. Tested it on another PC and it worked perfectly right away. If I produce an error, I'll be sure to let you know.

**Comment by bokerlol** [comment]
I wanted to update this with a potential 'solution' to the issue at hand considering I'm not the only one who ran into it. 

The only way I managed to get it to work on Firefox (Chrome you could just spam the extension icon for a while and it would eventually show.) was to do the following:

1: Open about:debugging#/runtime/this-firefox
2: Inspect 'TubeArchivist Companion'
3: In the top right, hit the three dots and choose 'Disable Pop-Up Auto Hide'
4: Click on the extension icon again and then do various things in your browser. 
5: Eventually, it will show up and you are able to put your information in. Sometimes it only took about 10 seconds to show. Other times, it would take upwards of a minute. 

Side note: I have a feeling something bigger is going on as the auto cookie import wouldn't work no matter what I did. It just labeled it as 'undefined' and did throw an error in console, which I will put below. 

![image](https://user-images.githubusercontent.com/48449854/224277002-7330e08b-1d11-4979-9412-e5c73bed4a10.png)

```
03:22:53.204 XHR PUT https://my.domain.com/api/cookie/

[HTTP/2 400 Bad Request 229ms]
```

Another note, I do _not_ get this cookie issue on a computer where the extension is working as intended.

Anyways, just wanted to throw that detail in there. Closing the issue since 'resolved'.
