### ISSUE TITLE
"Unexpected token '<', " <!doctype "... is not valid JSON"

### ISSUE THREAD

**Issue by EpicLPer** [tubearchivist/browser-extension#21]
Heya,

when I'm trying to set up the companion I simply get the following error after entering the URL:

```
Unexpected token '<', "
<!doctype "... is not valid JSON
```

I don't even have to enter a API key for it to display that error.
I'm hosting Tube Archivist on my Synology as a Docker container with the default port of 8000. If it's also important, I'm using Brave (which is Chromium based).

**Comment by bbilly1** [comment]
probably not a correct address for the TA url. What did you enter?

make sure it's from your example where synology is hosting tubearchivist, e.g.

`http://192.168.1.10:8000` obviously replacing the IP address with your synology server IP address.

**Comment by EpicLPer** [comment]
Nevermind, scrap this... I've discovered I'm an idiot and did indeed forget to add something to the URL to make it work...
Sorry ^^"

**Comment by Kozi801** [comment]
I have the same issue. Everything used to work and now suddenly I have this error in the companion. my address has not changed.

**Comment by bbilly1** [comment]
Also see here: https://github.com/tubearchivist/browser-extension/issues/52
