### ISSUE TITLE
no button on short videos

### ISSUE THREAD

**Issue by hafx** [tubearchivist/browser-extension#25]
Hi, 

### **First issue :** 
Sorry if I'm wrong, but I would like to know if I have to do something from my side to have the button to download directly from youtube short ?

The button appears with links "https://www.youtube.com/watch?v=xxxxxxxxxxx" but not with links like "https://www.youtube.com/shorts/xxxxxxxxxxx".

### **The second issue :** 
I need also sometimes to refresh (F5) the page with link like "https://www.youtube.com/watch?v=xxxxxxxxxxx" because the button doesn't appear.  

**Extensions :** 
- TubeArchivist Companion 0.2.0 with chromium (last version)

Thanks

**Comment by bbilly1** [comment]
Looks like YT move some things around, breaking our selector. Anybody wants to look into this?

**Comment by bbilly1** [comment]
OK, v0.2.2 adds download buttons to shorts links while browsing, your search results or subscription page. Adding button to the /shorts/ pages directly is on the roadmap and will happen at some point in the future.
