### ISSUE TITLE
Failing to login while exposing behind https proxy

### ISSUE THREAD

**Issue by alejakun** [tubearchivist/browser-extension#28]
Hi, I've setup my selfhosted my TA instance behind a reverse-proxy which redirects everything to https, that is how I access everything from within the browser, however while trying to login with the extension it fails. After looking at the inspector I see the following error:

```
Access to fetch at 'https://<redacted>/api/ping/' from origin 'chrome-extension://jjnkmicfnfojkkgobdfeieblocadmcie' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

My installed version is 0.2.1 and the reported error in the interface is `Could not connect to server`

**Comment by bbilly1** [comment]
That looks like a configuration issue on your proxy, the error suggests a missing header.
