### ISSUE TITLE
I've installed FF extension and I would to help

### ISSUE THREAD

**Issue by oyale** [tubearchivist/browser-extension#3]
Hi, @bbilly1. I am running a docker stack on localhost and have installed and configured the firefox extension.

It connects to the instance and displays a link on YT pages in its popup window. When clicked, it adds it to the download queue.

Ping me if you want me to test something :smile:

**Comment by bbilly1** [comment]
All great things start small. :-)

Do you want to improve on it? Reach out on Discord to coordinate!

**Comment by bbilly1** [comment]
@oyale I pushed a few changes, do you want to give it a try? You should now also be able to subscribe to channels, and playlists. Also There is a validator to only create download buttons for relevant links, videos, channels or playlists.

Let me know how this is working for you.
