### ISSUE TITLE
When used in combination with DeArrow (crowdsourced titles), many titles just show up blank.

### ISSUE THREAD

**Issue by transplier** [tubearchivist/browser-extension#33]
It's always a little awkward when two separate projects conflict like this, but I figured I'd raise an issue here. The relatively new extension DeArrow replaces clickbait video titles with crowdsourced improvements, and it has really improved the ergonomics of the site (maybe worth integrating with TA like Sponsorblock, but I digress...). Unfortunately, when both DeArrow and the TA extension are used at the same time and I visit a list of videos (subscriptions, channel), any video without a crowdsourced title improvement shows up with a blank title, i.e. 
![image](https://github.com/tubearchivist/browser-extension/assets/48895/753a49e8-ffea-4ed0-929e-c44773429f5a)

Perhaps one way to avoid needing close coordination between these two projects would be to make certain DOM modifications able to be disabled in the TA extension. I mostly use it to sync the cookie and on individual video pages, both of which work great today.

**Comment by barrelltitor** [comment]
The extension also breaks title formatting. Titles get  the following added to them:
thick
-thick
minusthick
minus-thick
Minus-thick

Disabling the TA extension fixes this

**Comment by Iliannnn** [comment]
> The extension also breaks title formatting. Titles get the following added to them: thick -thick minusthick minus-thick Minus-thick
> 
> Disabling the TA extension fixes this

Indeed, screenshots here:
https://github.com/tubearchivist/browser-extension/pull/37#issuecomment-2094800340
