### ISSUE TITLE
Extension stopped working after update to TubeArchivist v0.4.10

### ISSUE THREAD

**Issue by ewoks** [tubearchivist/browser-extension#43]
Not sure if there is some breaking change after last TubeArchivist ([v0.4.10](https://github.com/tubearchivist/tubearchivist/releases/tag/v0.4.10)) update, but it's extension v0.3.2 stopped working and shows "Can't connect to server".

Going directly to the url `http://<local-ip>:8888/api/ping/` answers with HTTP 200, pong and version, but extension can't make it. 

Please see attached screenshot of extension's worker
![image](https://github.com/user-attachments/assets/6f7a3055-14b2-4b48-8586-da1aebe54690)

- Revoking old and adding new API Key doesn't help
- Unchecking/checking "Sync YouTube cookies" doesn't help

I would like to emphasize this worked without issues for weeks before last update.

@bbilly1 please let me know if I can/should do some other debugging/logging that would be helpful.

**Comment by bbilly1** [comment]
There were no changes in v0.4.10, that was only a bump for yt-dlp. So if there were any changes, it was on your end.

You can get more logs and return statements by inspecting the background process, see Readme.

**Comment by ewoks** [comment]
Thanks for the comment @bbilly1 but there is nothing in the [Readme](https://github.com/tubearchivist/browser-extension/blob/master/README.md) about logs or background process besides what I already showed on the screenshot above. Could you please be a bit more specific. I didn't make any change, but for some reason extension can't connect to the service any more rendering errors:
![image](https://github.com/user-attachments/assets/b061ab35-c9a1-4216-b5cf-c97964f7e9df)

**Comment by bbilly1** [comment]
Please don't @ people, that creates unnecessary spam. Go to the Readme and search for background.js.

**Comment by ewoks** [comment]
I understand you are doing this for free and appreciate effort, didn't want to push, but I believe I was asking in a kind and polite way for the hint. 
This attitude comes from you pretty often lately and I hope whatever bothers you it goes away and wish you get well soon.

**Comment by bbilly1** [comment]
Let's stop here.
