### ISSUE TITLE
Fails without `http://` in the TA IP settings field

### ISSUE THREAD

**Issue by p0358** [tubearchivist/browser-extension#5]
Little improvement suggestion, as the option in settings says "Tube Archivist IP", but if you indeed enter just the IP, it is going to fail (because it does not default to http protocol apparently?). I think the code should attempt to prepend `http://` if no protocol is specified there already to avoid this, as it's not so obvious to figure out why it fails (if you check the logs and attempt to open the URL it tries to GET in a new tab, it will work...)

**Comment by bbilly1** [comment]
It is mentioned in the Readme though: https://github.com/tubearchivist/browser-extension#setup.

But you are right, this could be added automatically when saving the form if needed. 

Do you want to implement it? Please make a PR.

**Comment by bbilly1** [comment]
This is now implemented in v0.1, defaulting to `http://`.
