### ISSUE TITLE
Observer to inject buttons into youtube search page

### ISSUE THREAD

**Issue by bbilly1** [tubearchivist/browser-extension#7]
Documenting a snipped provided by @bakkot on how to inject a download button into youtube search results.

```js
function ensureTALinks() {
  let titles = document.querySelectorAll('#title-wrapper');
  for (let title of titles) {
    if (title.hasTA) continue;
    let titleLink = title.querySelector('#video-title')?.href;
    if (titleLink == null) continue;
    let link = document.createElement('a');
    link.href = '#';
    link.innerHTML = 'Send to TA';
    link.addEventListener('click', e => {
      e.preventDefault();
      alert(`do something with ${titleLink}`);
    });
    title.append(link);
    title.hasTA = true;
  }
}
ensureTALinks();

let observer = new MutationObserver(list => {
  if (list.some(i => i.type === 'childList' && i.addedNodes.length > 0)) {
    ensureTALinks();
  }
});

observer.observe(document.body, { attributes: false, childList: true, subtree: true });
```

Just keeping this here for future reference.

**Comment by pairofcrocs** [comment]
![browser-buttons](https://user-images.githubusercontent.com/34723037/198838051-32c3939d-edff-499b-9ab4-b98e7c7d4f60.svg)

Just as reference, the font used is Roboto Medium

**Comment by pairofcrocs** [comment]
![browser-buttons](https://user-images.githubusercontent.com/34723037/198838112-3a6a9e55-f7b1-4d17-8656-b6b64afd8037.svg)

Just as reference, the font used is Roboto Medium.

**Comment by bbilly1** [comment]
v0.1.0 is implementing the observer approach. Thanks for the input.
