### ISSUE TITLE
Support for Invidious

### ISSUE THREAD

**Issue by mobedoor** [tubearchivist/browser-extension#8]
Hi. Invidious is a privacy respecting frontend developed for youtube.
I'd like to request extending this extensions compatibility to Invidious. URL's scheme is identical to youtube which should be helpful if you decide to implement. Instances are listed [here](https://api.invidious.io/)
Thank you for your time.

**Comment by bbilly1** [comment]
Browser addons need to follow strict permissions, that includes, on which websites this addon is allowed to run. This project is: 
> A browser extension to bridge YouTube with [Tube Archivist](https://github.com/tubearchivist/tubearchivist).

And that's the permission this addon requires. I don't want to extend this beyond that, to a huge list of all the public instances, plus there are the selfhosted instances too...

This extension is mostly a convenience thing, so you don't have to copy paste things back and forth. Invidious is very much compatible with Tube Archivist, as both use the same IDs for videos/channels/playlists, so you can also just copy paste the IDs from invidious into the corresponding forms of Tube Archivist to download or subscribe to things.

**Comment by mobedoor** [comment]
Thank you for clarifying bbilly1 and the workaround.
