### ISSUE TITLE
Wrong hoverover text

### ISSUE THREAD

**Issue by pairofcrocs** [tubearchivist/browser-extension#9]
Button works as implied, but the hover over on subscribe shows video URL instead of the channel URL
![image](https://user-images.githubusercontent.com/34723037/204943030-30e75175-1cf2-4d13-ad3c-5666616760a5.png)

**Comment by bbilly1** [comment]
So this is correct, you are subscribing to the video, then Tube Archivist extracts the channel id for you: https://github.com/tubearchivist/tubearchivist/wiki/Channels#channels-overview. Subscribe button is like copy-pasting the current url into the subscribe form.

**Comment by pairofcrocs** [comment]
^
